/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.bumptech.glide;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int coordinatorLayoutStyle = 0x7f030081;
        public static final int font = 0x7f0300ac;
        public static final int fontProviderAuthority = 0x7f0300ae;
        public static final int fontProviderCerts = 0x7f0300af;
        public static final int fontProviderFetchStrategy = 0x7f0300b0;
        public static final int fontProviderFetchTimeout = 0x7f0300b1;
        public static final int fontProviderPackage = 0x7f0300b2;
        public static final int fontProviderQuery = 0x7f0300b3;
        public static final int fontStyle = 0x7f0300b4;
        public static final int fontWeight = 0x7f0300b5;
        public static final int keylines = 0x7f0300d9;
        public static final int layout_anchor = 0x7f0300dc;
        public static final int layout_anchorGravity = 0x7f0300dd;
        public static final int layout_behavior = 0x7f0300de;
        public static final int layout_dodgeInsetEdges = 0x7f03010a;
        public static final int layout_insetEdge = 0x7f030113;
        public static final int layout_keyline = 0x7f030114;
        public static final int statusBarBackground = 0x7f030169;
    }
    public static final class bool {
        private bool() {}

        public static final int abc_action_bar_embed_tabs = 0x7f040000;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f050066;
        public static final int notification_icon_bg_color = 0x7f050067;
        public static final int ripple_material_light = 0x7f050074;
        public static final int secondary_text_default_material_light = 0x7f050076;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f060053;
        public static final int compat_button_inset_vertical_material = 0